Fixup lcm for MacOS 12.6
First issue on darwin (pkg-conf missing pcre2, libsysprof-capture):

```
- Detecting CXX compile features - done
-- Found PkgConfig: /nix/store/svafyjg9cly5zrq6hvbd34d14szvx2l7-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2")
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.84.1
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre2-8', required by 'glib-2.0', not found
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre2-8', required by 'glib-2.0', not found
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre2-8', required by 'glib-2.0', not found
Package libpcre2-8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre2-8.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre2-8', required by 'glib-2.0', not found
-- Performing Test CMAKE_C_COMPILER_SUPPORTS__std_gnu99
-- Performing Test CMAKE_C_COMPILER_SUPPORTS__std_gnu99 - Success
-- Performing Test CMAKE_C_COMPILER_SUPPORTS__Wall
...skipping...
[ 38%] Linking C executable lcm-example
[ 39%] Linking C executable lcm-logplayer
1 error generated.
[ 41%] Linking C executable lcm-sink
[ 41%] Linking C executable lcm-source
make[2]: *** [lcm-logger/CMakeFiles/lcm-logger.dir/build.make:79: lcm-logger/CMakeFiles/lcm-logger.dir/lcm_logger.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:563: lcm-logger/CMakeFiles/lcm-logger.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 42%] Linking C executable lcm-tester
[ 43%] Linking C executable lcm-logfilter
[ 44%] Linking C executable lcm-buftest-receiver
[ 44%] Linking C executable lcm-buftest-sender
[ 44%] Built target lcm-logplayer
[ 44%] Built target lcm-example
[ 44%] Built target lcm-source
[ 44%] Built target lcm-sink
[ 44%] Built target lcm-tester
[ 44%] Built target lcm-logfilter
[ 44%] Built target lcm-buftest-receiver
[ 44%] Built target lcm-buftest-sender
[ 45%] Linking CXX shared library libgtest.dylib
[ 45%] Built target gtest
make: *** [Makefile:166: all] Error 2
```

Second issue on darwin (fdatasync does not exist):

```
-- Build files have been written to: /tmp/nix-build-lcm-1.5.2.drv-1/source/build
cmake: enabled parallel building
cmake: enabled parallel installing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
build flags: -j10 SHELL=/nix/store/5sq6n9cpwp3jlf8jvfa7apd4wh8wm4a5-bash-5.2p37/bin/bash
[  0%] Building C object lcm/CMakeFiles/lcm.dir/lcm.c.o
[  3%] Generating lcmUtilities.cmake
[  4%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_csharp.c.o
[  4%] Building C object lcm/CMakeFiles/lcm.dir/lcm_file.c.o
[  4%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_c.c.o
[  5%] Building C object lcm/CMakeFiles/lcm-static.dir/lcm_file.c.o
[  5%] Building C object lcm/CMakeFiles/lcm-static.dir/eventlog.c.o
[  5%] Building C object lcm/CMakeFiles/lcm-static.dir/lcm.c.o
[  6%] Building C object lcm/CMakeFiles/lcm.dir/eventlog.c.o
[  6%] Building CXX object test/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  6%] Built target lcm_use_file
[  6%] Building C object lcm/CMakeFiles/lcm-static.dir/lcm_memq.c.o
[  7%] Building C object lcm/CMakeFiles/lcm-static.dir/lcm_mpudpm.c.o
[  8%] Building C object lcm/CMakeFiles/lcm.dir/lcm_memq.c.o
[  8%] Building C object lcm/CMakeFiles/lcm-static.dir/lcm_tcpq.c.o
[  8%] Building C object lcm/CMakeFiles/lcm.dir/lcm_mpudpm.c.o
[  9%] Building C object lcm/CMakeFiles/lcm.dir/lcm_tcpq.c.o
[ 10%] Building C object lcm/CMakeFiles/lcm-static.dir/lcm_udpm.c.o
[ 11%] Building C object lcm/CMakeFiles/lcm-static.dir/ringbuffer.c.o
[ 11%] Building C object lcm/CMakeFiles/lcm.dir/lcm_udpm.c.o
[ 11%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_cpp.c.o
[ 12%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_go.c.o
[ 12%] Building C object lcm/CMakeFiles/lcm-static.dir/udpm_util.c.o
[ 13%] Building C object lcm/CMakeFiles/lcm-static.dir/lcmtypes/channel_port_map_update_t.c.o
[ 14%] Building C object lcm/CMakeFiles/lcm-static.dir/lcmtypes/channel_to_port_t.c.o
[ 15%] Building C object lcm/CMakeFiles/lcm.dir/ringbuffer.c.o
[ 16%] Building C object lcm/CMakeFiles/lcm.dir/udpm_util.c.o
[ 16%] Building C object lcm/CMakeFiles/lcm.dir/lcmtypes/channel_port_map_update_t.c.o
[ 17%] Building C object lcm/CMakeFiles/lcm.dir/lcmtypes/channel_to_port_t.c.o
[ 17%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_java.c.o
[ 18%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_lua.c.o
[ 18%] Linking C static library liblcm.a
[ 19%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_python.c.o
[ 19%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/getopt.c.o
[ 20%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/lcmgen.c.o
[ 21%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/main.c.o
[ 22%] Linking C shared library liblcm.dylib
[ 22%] Built target lcm-static
[ 22%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/tokenize.c.o
[ 23%] Building C object lcm-logger/CMakeFiles/lcm-logger.dir/lcm_logger.c.o
[ 23%] Building C object lcm-logger/CMakeFiles/lcm-logger.dir/glib_util.c.o
[ 24%] Building C object liblcm-test/CMakeFiles/lcm-sink.dir/lcm-sink.c.o
[ 25%] Building C object lcm-logger/CMakeFiles/lcm-logplayer.dir/lcm_logplayer.c.o
[ 26%] Linking C executable lcm-gen
[ 27%] Building C object liblcm-test/CMakeFiles/lcm-source.dir/lcm-source.c.o
[ 27%] Built target lcm
/tmp/nix-build-lcm-1.5.2.drv-1/source/lcm-logger/lcm_logger.c:432:13: error: call to undeclared function 'fdatasync'; ISO C99 and later do not support impl>
  432 |             fdatasync(fileno(logger->log->f));
      |             ^
1 error generated.
make[2]: *** [lcm-logger/CMakeFiles/lcm-logger.dir/build.make:79: lcm-logger/CMakeFiles/lcm-logger.dir/lcm_logger.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 27%] Building C object liblcm-test/CMakeFiles/lcm-tester.dir/lcm-tester.c.o
make[1]: *** [CMakeFiles/Makefile2:567: lcm-logger/CMakeFiles/lcm-logger.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Building C object liblcm-test/CMakeFiles/lcm-example.dir/lcm-example.c.o
[ 28%] Linking C executable lcm-sink
[ 28%] Linking C executable lcm-logplayer
[ 28%] Building C object liblcm-test/CMakeFiles/lcm-logfilter.dir/lcm-logfilter.c.o
[ 28%] Building C object liblcm-test/CMakeFiles/lcm-buftest-receiver.dir/buftest-receiver.c.o
[ 29%] Linking C executable lcm-source
[ 29%] Built target lcm-gen
[ 29%] Linking C executable lcm-example
[ 30%] Linking C executable lcm-tester
[ 30%] Built target lcm-sink
[ 30%] Built target lcm-logplayer
[ 31%] Linking C executable lcm-logfilter
[ 32%] Linking C executable lcm-buftest-receiver
[ 32%] Built target lcm-source
[ 32%] Built target lcm-example
[ 32%] Built target lcm-tester
[ 32%] Built target lcm-logfilter
[ 32%] Built target lcm-buftest-receiver
[ 33%] Linking CXX static library libgtest.a
[ 33%] Built target gtest
make: *** [Makefile:166: all] Error 2
```